# For readability and to prevent needless merge conflicts, follow all possible
# conventions in the official OpenAPI specification and documentation, including
# the order of fixed fields like paths and components, spacing, and quoting of
# strings. Pay attention to the rest of the file for any other conventions. Use
# one of the automated formatters in the resources below.
#
# Tip: Use https://editor-next.swagger.io/ for real-time, in-browser feedback.
#
# Resources:
# - https://spec.openapis.org/oas/v3.1.0.html - Official specification.
# - https://learn.openapis.org/specification/ - Official documentation.
# - https://swagger.io/docs/specification/ - Alternative documentation.
# - https://www.jetbrains.com/help/idea/openapi.html - PhpStorm features.
# - https://codifyformatter.org/yaml-formatter,
#   https://onlineyamltools.com/prettify-yaml - YAML formatters that follow the
#   official OpenAPI conventions. They are functionally identical. Warning: They
#   also strip comments and blank lines. Review diffs carefully to avoid losing
#   any.

openapi: 3.1.0
info:
  title: Experience Builder
  description: API Spec for Experience Builder
  version: 0.x

paths:
  '/api/layout/{entityTypeId}/{entityId}':
    get:
      parameters:
        - $ref: '#/components/parameters/entityTypeId'
        - $ref: '#/components/parameters/entityId'
      responses:
        '200':
          description: The layout
          content:
            application/json:
              examples:
                emptyComponentTree:
                  value:
                    layout:
                      uuid: root
                      nodeType: root
                      name: root
                      children: []
                    model: {}
                componentTreeWithSingleComponent:
                  value:
                    layout:
                      uuid: root
                      nodeType: root
                      name: root
                      children:
                        - uuid: bce8d97e-8d44-4609-adc3-5e1015342b49
                          nodeType: component
                          type: 'sdc_test:my-cta'
                    model:
                      bce8d97e-8d44-4609-adc3-5e1015342b49:
                        text: 'hello, world!'
                        href: 'https://drupal.org'
                        name: My Test CTA Component
              schema:
                type: object
                required:
                  - layout
                  - model
                properties:
                  layout:
                    $ref: '#/components/schemas/Layout'
                  model:
                    $ref: '#/components/schemas/Model'
  '/api/preview/{entityTypeId}/{entityId}':
    post:
      parameters:
        - $ref: '#/components/parameters/entityTypeId'
        - $ref: '#/components/parameters/entityId'
      requestBody:
        $ref: '#/components/requestBodies/Layout'
      responses:
        '200':
          description: Generated preview successfully
  /xb-components:
    get:
      responses:
        '200':
          description: All available components
          content:
            application/json:
              examples:
                singleAvailableComponent:
                  value:
                    'sdc_test:my-cta':
                      id: 'sdc_test:my-cta'
                      name: Call to Action
                      metadata:
                        path: >-
                          core/modules/system/tests/modules/sdc_test/components/my-cta
                        documentation: >-
                          No documentation found. Add a README.md in your
                          component directory.
                        status: stable
                        machineName: my-cta
                        name: Call to Action
                        group: All Components
                        schema:
                          type: object
                          required:
                            - text
                          properties:
                            text:
                              type:
                                - string
                                - object
                              title: Title
                              description: The title for the cta
                              examples:
                                - Press
                                - Submit now
                            href:
                              type:
                                - string
                                - object
                              title: URL
                              format: uri
                            target:
                              type:
                                - string
                                - object
                              title: Target
                              enum:
                                - ''
                                - _blank
                            attributes:
                              type:
                                - Drupal\Core\Template\Attribute
                                - object
                              name: Attributes
                          additionalProperties: false
                      description: Call to action link.
                      mandatorySchemas: true
                      slots: []
              schema:
                type: object
                minProperties: 1
                # @see \Drupal\Core\Plugin\Component::$machineName
                patternProperties:
                  '^\\[a-zA-Z0-9_-]:[a-zA-Z0-9_-]$':
                    $ref: '#/components/schemas/Component'
  '/xb-field-form/{entityTypeId}/{entityId}':
    get:
      parameters:
        - $ref: '#/components/parameters/entityTypeId'
        - $ref: '#/components/parameters/entityId'
      responses:
        '200':
          description: The form
  '/xb-render-component/{componentId}':
    get:
      parameters:
        - name: componentId
          in: path
          required: true
          description: TODO
          schema:
            type: string
      responses:
        '200':
          description: The rendered component, along with relevant metadata for re-rendering it client-side.
          content:
            application/json:
              schema:
                type: object
                required:
                  - id
                  - markup
                  - props
                  - metadata
                properties:
                  id:
                    type: string
                    description: The component ID
                  markup:
                    type: string
                  # @see \Drupal\Core\Theme\Component\ComponentMetadata
                  metadata:
                    type: object
                  props:
                    type: object
                additionalProperties: false
  '/xb/api/entity-form/{entityTypeId}/{entityId}/{entityFormMode}':
    description: Fetches the entity form with the specified form mode
    get:
      parameters:
        - $ref: '#/components/parameters/entityTypeId'
        - $ref: '#/components/parameters/entityId'
        - name: entityFormMode
          in: path
          required: true
          description: The entity form mode of the form to retrieve
          schema:
            type: string
          example: default
      responses:
        '200':
          $ref: '#/components/responses/FormResponse'
  '/xb/api/entity-form/{entityTypeId}/{entityId}':
    description: Fetches the entity form with the "default" form mode
    get:
      parameters:
        - $ref: '#/components/parameters/entityTypeId'
        - $ref: '#/components/parameters/entityId'
      responses:
        '200':
          $ref: '#/components/responses/FormResponse'

components:
  schemas:
    Component:
      title: Component
      type: object
      required:
        - name
        - id
        - metadata
        - field_data
        - default_markup
      properties:
        name:
          type: string
          description: The component name
        id:
          type: string
          description: The component id
        # @see \Drupal\Core\Theme\Component\ComponentMetadata
        metadata:
          type: object
        field_data:
          type: object
          # Keys are props for this SDC. Only required SDC props are required here.
          additionalProperties:
            type: object
            required:
              - sourceType
              - expression
              - required
            properties:
              sourceType:
                type: string
              expression:
                type: string
              required:
                type: boolean
              default_values:
                type:
                  - string
                  - integer
                  - number
                  - boolean
                  - object
        default_markup:
          type: string
        dynamic_prop_source_candidates:
          type: object
      additionalProperties: false
    Layout:
      title: layout
      type: object
      required:
        - uuid
        - nodeType
      additionalProperties: false
      properties:
        uuid:
          type: string
          description: The UUID of the layout
        nodeType:
          type: string
          description: The layout type
        type:
          type: string
        name:
          type: string
          description: The name of the layout
        children:
          type: array
          description: Array of layouts
          items:
            $ref: '#/components/schemas/Layout'
    LayoutPreview:
      title: LayoutPreview
      type: object
      additionalProperties: false
      properties:
        layout:
          $ref: '#/components/schemas/Layout'
        model:
          $ref: '#/components/schemas/Model'
    Model:
      title: model
      type: object
  responses:
    FormResponse:
      description: The form
      content:
        application/json:
          examples:
            arbitraryForm:
              value:
                html: <form></form>
          schema:
            type: object
            required:
              - html
            properties:
              html:
                schema:
                  type: string
  parameters:
    entityTypeId:
      name: entityTypeId
      in: path
      required: true
      description: The entity type ID
      schema:
        type: string
      example: node
    entityId:
      name: entityId
      in: path
      required: true
      description: The entity ID
      schema:
        type: integer
      examples:
        arbitraryEntityId:
          value: 42
  requestBodies:
    Layout:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/LayoutPreview'
